project_name: dev-swarm

before:
  hooks:
    - go mod tidy

builds:
  - id: dev-swarm
    main: ./cmd/dev-swarm
    binary: dev-swarm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/nathanbarrett/dev-swarm-go/pkg/version.Version={{.Version}}
      - -X github.com/nathanbarrett/dev-swarm-go/pkg/version.Commit={{.Commit}}
      - -X github.com/nathanbarrett/dev-swarm-go/pkg/version.Date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: nathanbarrett
    name: dev-swarm-go
  draft: false
  prerelease: auto
